# Generated by Django 5.0.3 on 2024-04-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='periodic_task',
            field=models.ManyToManyField(to='django_celery_beat.periodictask'),
        ),
    ]
