# Generated by Django 5.0.3 on 2024-03-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='groupaccounts',
            table='group_accounts',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
