# Generated by Django 5.0.3 on 2024-04-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_periodic_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='periodic_task',
            new_name='periodic_tasks',
        ),
    ]
