# Generated by Django 5.0.3 on 2024-03-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_balance',
            field=models.IntegerField(verbose_name='Активный баланс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='safe_balance',
            field=models.IntegerField(verbose_name='Сбережения'),
        ),
    ]
