version: "3.11"

services:
  backend:
    build: .
    image: django_grad:v1
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
#    command: ./run.sh
    restart: always
    environment:
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: password
    env_file:
      - compose/.compose.env
    depends_on:
      - postgres
      - cache



    #        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': os.environ.get("DATABASE NAME"),
#        # "PHIN",
#        "USER": os.environ.get("DATABASE USER"),
#            # "slava_final",
#        "PASSWORD": os.environ.get("DATABASE PASSWORD"),
#            # "12345678",
#        "HOST": os.environ.get("DATABASE HOST"),
#            # "127.0.0.1",  # IP адрес или домен СУБД.
#        "PORT": 5432,
#    }
  postgres:
    image: postgres:14.0
    environment:
      POSTGRES_DB: phin
      POSTGRES_USER: slava_final
      POSTGRES_PASSWORD: 12345678

    volumes:
      - "./pg_data:/var/lib/postgresql/data"


  pgadmin:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
      PGADMIN_LISTEN_PORT: "8080"
    ports:
    - "8080:8080"


  nginx:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - "./compose/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    depends_on:
      - backend



  cache:
    restart: always
    image: redis:7.2.4-alpine
