# Generated by Django 5.0.3 on 2024-03-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField(verbose_name='Сумма')),
                ('type', models.CharField(choices=[('I', 'Income'), ('E', 'Expence')], max_length=1, verbose_name='Тип изменения баланса')),
                ('necessity', models.BooleanField(blank=True, null=True, verbose_name='Необходимость траты')),
                ('regularity', models.BooleanField(verbose_name='Регулярность')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(verbose_name='Содержание')),
                ('time_period_start', models.DateTimeField(verbose_name='Начало промежутка времени')),
                ('time_period_end', models.DateTimeField(verbose_name='Конец промежутка времени')),
            ],
        ),
    ]
