# Generated by Django 5.0.3 on 2024-04-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField(verbose_name='Сумма')),
                ('necessity', models.BooleanField(verbose_name='Необходимость траты')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('type', models.CharField(choices=[('I', 'Income'), ('E', 'Expence')], max_length=1, verbose_name='Тип изменения баланса')),
            ],
            options={
                'db_table': 'balance_changes',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_private', models.BooleanField(verbose_name='Приватность')),
                ('type', models.CharField(choices=[('I', 'Income'), ('E', 'Expence')], max_length=1, verbose_name='Тип изменения баланса')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='RegularBalanceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField(verbose_name='Сумма')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('regularity', models.DateTimeField(verbose_name='Регулярность')),
                ('type', models.CharField(choices=[('I', 'Income'), ('E', 'Expence')], max_length=1, verbose_name='Тип изменения баланса')),
            ],
            options={
                'db_table': 'regular_balance_changes',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(verbose_name='Содержание')),
                ('time_period_start', models.DateTimeField(verbose_name='Начало промежутка времени')),
                ('time_period_end', models.DateTimeField(verbose_name='Конец промежутка времени')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
