# Generated by Django 5.0.3 on 2024-03-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancechange',
            name='sum',
            field=models.IntegerField(verbose_name='Сумма'),
        ),
    ]
