# Generated by Django 5.0.3 on 2024-03-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expences',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='incomes',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='expecescategories',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='expences',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expences',
            name='necessity',
            field=models.CharField(max_length=255, verbose_name='Необходимость траты'),
        ),
        migrations.AlterField(
            model_name='expences',
            name='sum',
            field=models.IntegerField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='regularity',
            field=models.CharField(max_length=255, verbose_name='Регулярность дохода'),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='sum',
            field=models.IntegerField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='incomesources',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
