# Generated by Django 5.0.3 on 2024-04-07 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancechange',
            name='necessity',
        ),
    ]
