# Generated by Django 5.0.3 on 2024-04-11 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reports',
        ),
    ]
