# Generated by Django 5.0.3 on 2024-03-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancechange',
            old_name='user_id',
            new_name='user',
        ),
    ]
