# Generated by Django 5.0.3 on 2024-03-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_user_id_balancechange_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancechange',
            name='regularity',
        ),
    ]
